### ISSUE TITLE
Polishing issue

### ISSUE THREAD

**Issue by claczny** [CSB5/OPERA-MS#23]
Hi,

it seems that all steps until the "Polishing" finished fine but in the last step ( `Polishing [9/9]`), I received the following error in `/mnt/lscratch/users/claczny/ont/testing/results/assembly/operams/lr-sr/intermediate_files/polished_assembly/pilon.err`:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArithmeticException: / by zero
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:70)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:52)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:98)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
        ... 6 more
```

Moreover, I get many lines like the following in the output (log file) :
```
Use of uninitialized value $contig_name in concatenation (.) or string at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> lin
e 112467.
Use of uninitialized value $contig_name in hash element at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112467.
Use of uninitialized value in concatenation (.) or string at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112467.
Use of uninitialized value $contig_name in concatenation (.) or string at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112469.
Use of uninitialized value $contig_name in hash element at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112469.
Use of uninitialized value in concatenation (.) or string at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112469.
Use of uninitialized value $contig_name in concatenation (.) or string at /scratch/users/claczny/ont/apps/software/OPERA-MS/OPERA-MS.pl line 1221, <FILE> line 112471.
```

 as well as the following in the output (log file) :
```
ERROR: Did not find fasta records in "/mnt/lscratch/users/claczny/ont/testing/results/assembly/operams/lr-sr//opera_ms_clusters/cluster_26.fasta".
```

Even though I could also probably just skip the polishing step, your input is greatly appreciated to get it to work :)

Best,

Cedric

[UPDATE]
Further inspecting the output, I also discovered
```
Illegal division by zero at /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/cluster_info.pl line 224.
``` 
in the stdout line following
```
/scratch/users/claczny/ont/apps/software/OPERA-MS/utils/perl /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/cluster_info.pl ...
```

[UPDATE2]
In `results/assembly/operams/lr-sr//intermediate_files/opera_long_read/g_assembly_stats.err`, I get 

```
 *** Reading coverage file /mnt/lscratch/users/claczny/ont/testing/results/assembly/operams/lr-sr//intermediate_files/coverage_estimation/contigs_340_80
 *** Reading reference clustering file /mnt/lscratch/users/claczny/ont/testing/results/assembly/operams/lr-sr//intermediate_files/reference_clustering/cluster_species.dat
Use of uninitialized value $scaffold_seq in subtraction (-) at /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/generate_assembly_stats.pl line 219, <SCAFFOLDSEQ> line 219468.
Use of uninitialized value $scaffold_seq in subtraction (-) at /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/generate_assembly_stats.pl line 219, <SCAFFOLDSEQ> line 219468.
Use of uninitialized value $scaffold_seq in subtraction (-) at /scratch/users/claczny/ont/apps/software/OPERA-MS//bin/generate_assembly_stats.pl line 219, <SCAFFOLDSEQ> line 219468.
...
```

**Comment by dbertran78** [comment]
Resolved off line.
