### ISSUE TITLE
Issues in gap filling - causing unusable contigs.fasta?

### ISSUE THREAD

**Issue by ikeenum** [CSB5/OPERA-MS#33]
Hello,
I am having issues in gap filling and get the warning "Use of uninitialized value $contig_name in concatenation (.) or string at" or Use of uninitialized value $contig_name in hash element at" "Use of uninitialized value in concatenation" for many lines (> 100).

When running OPERA-MS without polishing it would claim it had finished successfully but I have been unable to utilize tools such as MetaQuast because the contig file is unreadable. 

With polishing, OPERA errors out with "Error in during pilon. Please see pilot.err/pilon.out  for details - pilon.err contains the error 
"
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArithmeticException: / by zero
        at org.broadinstitute.pilon.GenomeFile.contigRegions(GenomeFile.scala:70)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at org.broadinstitute.pilon.GenomeFile$$anonfun$2.apply(GenomeFile.scala:52)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.broadinstitute.pilon.GenomeFile.<init>(GenomeFile.scala:52)
        at org.broadinstitute.pilon.Pilon$.main(Pilon.scala:98)
        at org.broadinstitute.pilon.Pilon.main(Pilon.scala)
        ... 6 more"

[contigs.txt](https://github.com/CSB5/OPERA-MS/files/3735610/contigs.txt)

[OPERA-MS-LOG.tar.gz](https://github.com/CSB5/OPERA-MS/files/3735560/OPERA-MS-LOG.tar.gz)

**Comment by ikeenum** [comment]
I just wanted to follow up with this to see if you had any advice. I can email fasta files I am using if that is helpful!

**Comment by dbertran78** [comment]
Hi ikeenum,
I am sorry for the late reply.
I have actually looked into your log files, and I was not able to identify the problem.
I will be great if you could share with us the fasta files, that we could try to reproduce and correct the  error you encounter.

Thank you for understanding and help.

**Comment by ikeenum** [comment]
Attached is a link to the nanopore and illumina reads! I hope they provide
some insight! We are really excited about the software! We have gotten
these reads to run through Megahit, Canu, Flye and Hybrid spades so we are
fairly certain the reads files are not the issue.
 Archive.zip
<https://drive.google.com/a/vt.edu/file/d/1Yd0Zc7_b2Fk04uCC_4gsmxn1-5cPXI6p/view?usp=drive_web>


Ishi Keenum







On Oct 29, 2019, at 11:00 PM, dbertran78 <notifications@github.com> wrote:

Hi ikeenum,
I am sorry for the late reply.
I have actually looked into your log files, and I was not able to identify
the problem.
I will be great if you could share with us the fasta files, that we could
try to reproduce and correct the error you encounter.

Thank you for understanding and help.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CSB5/OPERA-MS/issues/33?email_source=notifications&email_token=ALWMNG3TBELT44RHYS2KSX3QRD2FVA5CNFSM4JBOS2WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECSYJTA#issuecomment-547718348>,
or unsubscribe

**Comment by ikeenum** [comment]
Any update on this? Excited to see the results!

**Comment by dbertran78** [comment]
Dear ikeenum,
I am actually not able to download your file.
Can we try to solve this problem offline. 
You can contact me at bertrandd@gis.a-star.edu.sg

Best regards,

--- Denis
