### ISSUE TITLE
gap_filling.err -  Remap.py

### ISSUE THREAD

**Issue by krithikaarumugam** [CSB5/OPERA-MS#40]
Hi,

I installed the latest version of OPERA-MS ( v0.8.3 ) and seem to get the following error during the gap filling stage,

Traceback (most recent call last):
  File "/export2/home/krithika/tools/assemblers/opera-ms/OPERA-MS//OPERA-LG/bin//Remap.py", line 253, in <module>
    main(sys.argv[1:])
  File "/export2/home/krithika/tools/assemblers/opera-ms/OPERA-MS//OPERA-LG/bin//Remap.py", line 207, in main
    contig_seq = get_sequences(contig_path, valid_contig_map, contig_mapping_ID)
  File "/export2/home/krithika/tools/assemblers/opera-ms/OPERA-MS//OPERA-LG/bin//Remap.py", line 91, in get_sequences
    c_seq_rev = reverse_complement(seq)
  File "/export2/home/krithika/tools/assemblers/opera-ms/OPERA-MS//OPERA-LG/bin//Remap.py", line 14, in reverse_complement
    return ''.join([complement[base] for base in dna[::-1]])
KeyError: 'N' 

I have attached the log files.
[OPERA-MS-LOG.tar.gz](https://github.com/CSB5/OPERA-MS/files/4575012/OPERA-MS-LOG.tar.gz)
[gap_filling.err.gz](https://github.com/CSB5/OPERA-MS/files/4575025/gap_filling.err.gz)

After adding extra key:value - N:N in line 13 of Remap.py did not cause the gap_filling error and the job finished successfully. However am not sure if that's the real cause of the error. Please advise.
(OPERA-MS finished without any errors when I had tested it on another dataset though)

Thank you!

Regards,
Krithika

**Comment by dbertran78** [comment]
Dear Krithika,
Thank you for pointing us to this problem.
We will update the Remap.py code to allow for sequence with N.

Best regards,

--- Denis
