### ISSUE TITLE
Error during SPADES

### ISSUE THREAD

**Issue by Unaimend** [CSB5/OPERA-MS#76]
Hello OPERA-MS team,
After installing OPERA-MS like specified in 
https://github.com/CSB5/OPERA-MS/issues/48

I get the following error
```
(ins)(operams) [sukem127@caucluster1 intermediate_files]$ cat spades.err 
Traceback (most recent call last):
  File "/zfshome/sukem127/git_clones/OPERA-MS//tools_opera_ms//SPAdes-3.13.0-Linux/bin//spades.py", line 1093, in <module>
    main(sys.argv)
  File "/zfshome/sukem127/git_clones/OPERA-MS//tools_opera_ms//SPAdes-3.13.0-Linux/bin//spades.py", line 714, in main
    print_used_values(cfg, log)
  File "/zfshome/sukem127/git_clones/OPERA-MS//tools_opera_ms//SPAdes-3.13.0-Linux/bin//spades.py", line 110, in print_used_values
    dataset_data = pyyaml.load(open(cfg["dataset"].yaml_filename, 'r'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/__init__.py", line 72, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zfshome/sukem127/git_clones/OPERA-MS/tools_opera_ms/SPAdes-3.13.0-Linux/share/spades/pyyaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Hashable'
```
Related issue
https://github.com/ablab/spades/issues/863

The problem is that you are using an older version of spades
Quickfix seems to be to just downgrade your python version to 3.9

**Comment by jsgounot** [comment]
Hi,

good catch, I guess they upgraded default python version since I made this comment.
Thank you!

JS
