### ISSUE TITLE
Error in generating OPERA‐MS‐DB from GTDB release

### ISSUE THREAD

**Issue by ValeriiaLadyhina** [CSB5/OPERA-MS#88]
Hi! 

I have an error in step 4 of database installation, can you please help me to solve it:
"
python /export/opt/sw/opera-ms/0.8.3/OPERA-MS/src_utils/make_operams_db_from_gtdb.py gtdb_genomes_reps_r214.tar.gz all_taxonomy_r214.tsv.gz
Read taxonomy file
Check taxonomic information
Read genome file
Traceback (most recent call last):
  File "/export/opt/sw/opera-ms/0.8.3/OPERA-MS/src_utils/make_operams_db_from_gtdb.py", line 148, in <module>
    main()
  File "/export/opt/sw/opera-ms/0.8.3/OPERA-MS/src_utils/make_operams_db_from_gtdb.py", line 145, in main
    process(args)
  File "/export/opt/sw/opera-ms/0.8.3/OPERA-MS/src_utils/make_operams_db_from_gtdb.py", line 48, in process
    fnames = sorted(
  File "/export/opt/sw/opera-ms/0.8.3/OPERA-MS/src_utils/make_operams_db_from_gtdb.py", line 48, in <genexpr>
    fnames = sorted(
  File "/export/home/valeriia/miniforge3/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 3585: invalid start byte "

I was also a bit confused that in step 2 it is suggested to rm gtdb_genomes_reps_r214.tar.gz , although it is used again in step 5.

Thank you in advance.

**Comment by jsgounot** [comment]
Hi,

thanks for reporting the issue. It's a mistake in the wiki command line, I fixed the wiki page but here is the command line you should use (if you used the same file names as in the wiki):

```
python {OPERA-MS}/src_utils/make_operams_db_from_gtdb.py all_genomes.txt.gz all_taxonomy_r214.tsv.gz
```

With `{OPERA-MS}` being your OPERA-MS folder.

Hope this will resolve your issue, please let me know if it persists or if you have another issue, I recently added this method.

JS

**Comment by ValeriiaLadyhina** [comment]
Thank you! It worked.
